# Generated by Django 4.2.5 on 2023-10-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetxt',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
