# Generated by Django 4.2.5 on 2023-10-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_filemodel_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileComparisonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_result', models.FloatField()),
                ('other_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_file', to='base.filemodel')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file', to='base.filemodel')),
            ],
        ),
    ]
