# Generated by Django 4.2.5 on 2023-12-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidetection',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.fileimage'),
        ),
    ]
