# Generated by Django 4.2.5 on 2023-12-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_aidetection_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidetection',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='aidetection',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
